[package]
name = "wraith_sdl2"
version = "0.1.0"
edition = "2018"

[dependencies]
raw-window-handle = "0.3"
rectangle-pack = "0.4.2"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf","image","gfx","mixer","raw-window-handle","unsafe_textures"]
